classify({'abstract-art', 'realism'});
classify({'abstract-art', 'impressionism'});
classify({'abstract-art', 'ink-and-wash-painting'});
classify({'abstract-art', 'northern-renaissance'});
classify({'ink-and-wash-painting', 'realism'});
classify({'ink-and-wash-painting', 'impressionism'});
classify({'ink-and-wash-painting', 'northern-renaissance'});
classify({'impressionism', 'realism'});
classify({'impressionism', 'northern-renaissance'});
